package salmans;

import java.util.ArrayList;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Oscar
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        panel_add.setVisible(true);
        panel_mod.setVisible(false);
        panel_del.setVisible(false);
        warning.setVisible(false);
        panel_remIng.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Producto = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        panel_add = new javax.swing.JPanel();
        tf_nombreProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spinner_precio = new javax.swing.JSpinner();
        cb_prodAdd = new javax.swing.JComboBox();
        spinner_tiempo = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_nProd = new javax.swing.JTable();
        ok_Agregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panel_mod = new javax.swing.JPanel();
        tf_modName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        spinner_modPrice = new javax.swing.JSpinner();
        spinner_modTime = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_modProd = new javax.swing.JTable();
        ok_Mod = new javax.swing.JButton();
        cb_modProd = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        panel_del = new javax.swing.JPanel();
        ok_Agregar2 = new javax.swing.JButton();
        cb_delProd = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        warning = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        modificar = new javax.swing.JLabel();
        agregar = new javax.swing.JLabel();
        eliminar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Ingrediente = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        panel_addIng = new javax.swing.JPanel();
        ok_Agregar4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        tf_nameIng = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_desc = new javax.swing.JTextField();
        panel_remIng = new javax.swing.JPanel();
        ok_Agregar3 = new javax.swing.JButton();
        cb_delIng = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        agregar1 = new javax.swing.JLabel();
        eliminar1 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productoButton = new javax.swing.JLabel();
        ingredienteButton = new javax.swing.JLabel();
        cocinaButton = new javax.swing.JLabel();
        entregaButton = new javax.swing.JLabel();
        salirButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.setLayout(null);

        panel_add.setOpaque(false);
        panel_add.setLayout(null);

        tf_nombreProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreProdActionPerformed(evt);
            }
        });
        panel_add.add(tf_nombreProd);
        tf_nombreProd.setBounds(150, 20, 130, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/nombre.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        panel_add.add(jLabel5);
        jLabel5.setBounds(30, 20, 110, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/precio.jpg"))); // NOI18N
        panel_add.add(jLabel6);
        jLabel6.setBounds(30, 60, 110, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/ingredientes.jpg"))); // NOI18N
        panel_add.add(jLabel8);
        jLabel8.setBounds(30, 100, 110, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/tiempo.jpg"))); // NOI18N
        panel_add.add(jLabel9);
        jLabel9.setBounds(30, 210, 130, 30);

        spinner_precio.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 5));
        panel_add.add(spinner_precio);
        spinner_precio.setBounds(150, 60, 70, 30);

        panel_add.add(cb_prodAdd);
        cb_prodAdd.setBounds(150, 100, 110, 30);

        spinner_tiempo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 10));
        panel_add.add(spinner_tiempo);
        spinner_tiempo.setBounds(170, 210, 70, 30);

        tabla_nProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tabla_nProd);

        panel_add.add(jScrollPane1);
        jScrollPane1.setBounds(30, 140, 250, 60);

        ok_Agregar.setText("OK");
        ok_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_AgregarMouseClicked(evt);
            }
        });
        panel_add.add(ok_Agregar);
        ok_Agregar.setBounds(110, 250, 90, 26);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/plus.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panel_add.add(jLabel3);
        jLabel3.setBounds(260, 100, 30, 30);

        jPanel2.add(panel_add);
        panel_add.setBounds(50, 100, 300, 290);

        panel_mod.setOpaque(false);
        panel_mod.setLayout(null);

        tf_modName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_modNameActionPerformed(evt);
            }
        });
        panel_mod.add(tf_modName);
        tf_modName.setBounds(150, 60, 130, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/nombre.jpg"))); // NOI18N
        jLabel11.setText("jLabel5");
        panel_mod.add(jLabel11);
        jLabel11.setBounds(30, 60, 110, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/precio.jpg"))); // NOI18N
        panel_mod.add(jLabel12);
        jLabel12.setBounds(30, 100, 110, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/tiempo.jpg"))); // NOI18N
        panel_mod.add(jLabel14);
        jLabel14.setBounds(30, 210, 130, 30);

        spinner_modPrice.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 5));
        panel_mod.add(spinner_modPrice);
        spinner_modPrice.setBounds(150, 100, 70, 30);

        spinner_modTime.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 10));
        panel_mod.add(spinner_modTime);
        spinner_modTime.setBounds(170, 210, 70, 30);

        tabla_modProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad"
            }
        ));
        jScrollPane2.setViewportView(tabla_modProd);

        panel_mod.add(jScrollPane2);
        jScrollPane2.setBounds(30, 140, 250, 60);

        ok_Mod.setText("OK");
        ok_Mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_ModMouseClicked(evt);
            }
        });
        panel_mod.add(ok_Mod);
        ok_Mod.setBounds(110, 260, 90, 26);

        cb_modProd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_modProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_modProdActionPerformed(evt);
            }
        });
        panel_mod.add(cb_modProd);
        cb_modProd.setBounds(140, 20, 140, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/select.png"))); // NOI18N
        panel_mod.add(jLabel16);
        jLabel16.setBounds(30, 20, 110, 30);

        jPanel2.add(panel_mod);
        panel_mod.setBounds(50, 100, 300, 290);

        panel_del.setOpaque(false);
        panel_del.setLayout(null);

        ok_Agregar2.setText("OK");
        ok_Agregar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_Agregar2MouseClicked(evt);
            }
        });
        panel_del.add(ok_Agregar2);
        ok_Agregar2.setBounds(100, 120, 90, 30);

        cb_delProd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_delProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_delProdActionPerformed(evt);
            }
        });
        panel_del.add(cb_delProd);
        cb_delProd.setBounds(150, 80, 140, 30);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/select.png"))); // NOI18N
        panel_del.add(jLabel22);
        jLabel22.setBounds(40, 80, 110, 30);

        jPanel2.add(panel_del);
        panel_del.setBounds(50, 100, 300, 290);

        warning.setOpaque(false);
        warning.setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/warning.png"))); // NOI18N
        warning.add(jLabel13);
        jLabel13.setBounds(270, 0, 30, 30);

        jLabel10.setFont(new java.awt.Font("Bangers", 1, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NO HAY PRODUCTOS ");
        warning.add(jLabel10);
        jLabel10.setBounds(50, 0, 230, 30);

        jPanel2.add(warning);
        warning.setBounds(50, 100, 300, 290);

        jLabel7.setFont(new java.awt.Font("Bangers", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRODUCTO");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(220, 30, 220, 70);

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/modificar.png"))); // NOI18N
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });
        jPanel2.add(modificar);
        modificar.setBounds(380, 220, 240, 60);

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/add.png"))); // NOI18N
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });
        jPanel2.add(agregar);
        agregar.setBounds(380, 160, 240, 60);

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/eliminar.png"))); // NOI18N
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });
        jPanel2.add(eliminar);
        eliminar.setBounds(380, 280, 240, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/fondo.jpg"))); // NOI18N
        jLabel4.setText("jLabel2");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 620, 430);

        javax.swing.GroupLayout ProductoLayout = new javax.swing.GroupLayout(Producto.getContentPane());
        Producto.getContentPane().setLayout(ProductoLayout);
        ProductoLayout.setHorizontalGroup(
            ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        ProductoLayout.setVerticalGroup(
            ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setLayout(null);

        panel_addIng.setOpaque(false);
        panel_addIng.setLayout(null);

        ok_Agregar4.setText("OK");
        ok_Agregar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_Agregar4MouseClicked(evt);
            }
        });
        panel_addIng.add(ok_Agregar4);
        ok_Agregar4.setBounds(110, 110, 90, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/nombre.jpg"))); // NOI18N
        panel_addIng.add(jLabel15);
        jLabel15.setBounds(30, 30, 120, 20);
        panel_addIng.add(tf_nameIng);
        tf_nameIng.setBounds(160, 30, 110, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/desc.png"))); // NOI18N
        panel_addIng.add(jLabel17);
        jLabel17.setBounds(30, 70, 120, 20);
        panel_addIng.add(tf_desc);
        tf_desc.setBounds(160, 70, 110, 30);

        jPanel3.add(panel_addIng);
        panel_addIng.setBounds(50, 100, 300, 160);

        panel_remIng.setOpaque(false);
        panel_remIng.setLayout(null);

        ok_Agregar3.setText("OK");
        ok_Agregar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_Agregar3MouseClicked(evt);
            }
        });
        panel_remIng.add(ok_Agregar3);
        ok_Agregar3.setBounds(100, 90, 90, 30);

        cb_delIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_delIngActionPerformed(evt);
            }
        });
        panel_remIng.add(cb_delIng);
        cb_delIng.setBounds(140, 40, 140, 30);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/select.png"))); // NOI18N
        panel_remIng.add(jLabel26);
        jLabel26.setBounds(30, 40, 110, 30);

        jPanel3.add(panel_remIng);
        panel_remIng.setBounds(50, 100, 300, 160);

        jLabel29.setFont(new java.awt.Font("Bangers", 1, 48)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("ingredientes");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(190, 30, 270, 70);

        agregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/add.png"))); // NOI18N
        agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar1MouseClicked(evt);
            }
        });
        jPanel3.add(agregar1);
        agregar1.setBounds(380, 120, 240, 60);

        eliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/eliminar.png"))); // NOI18N
        eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar1MouseClicked(evt);
            }
        });
        jPanel3.add(eliminar1);
        eliminar1.setBounds(380, 180, 240, 60);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/fondo.jpg"))); // NOI18N
        jLabel30.setText("jLabel2");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(0, 0, 620, 290);

        javax.swing.GroupLayout IngredienteLayout = new javax.swing.GroupLayout(Ingrediente.getContentPane());
        Ingrediente.getContentPane().setLayout(IngredienteLayout);
        IngredienteLayout.setHorizontalGroup(
            IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngredienteLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        IngredienteLayout.setVerticalGroup(
            IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngredienteLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/logo.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 30, 540, 120);

        productoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/producto.png"))); // NOI18N
        productoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productoButtonMouseClicked(evt);
            }
        });
        jPanel1.add(productoButton);
        productoButton.setBounds(0, 190, 250, 50);

        ingredienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/ingredientes.png"))); // NOI18N
        ingredienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingredienteButtonMouseClicked(evt);
            }
        });
        jPanel1.add(ingredienteButton);
        ingredienteButton.setBounds(0, 260, 250, 48);

        cocinaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/cocina.png"))); // NOI18N
        jPanel1.add(cocinaButton);
        cocinaButton.setBounds(280, 190, 250, 50);

        entregaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/entregas.png"))); // NOI18N
        jPanel1.add(entregaButton);
        entregaButton.setBounds(280, 260, 250, 48);

        salirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/salir.png"))); // NOI18N
        salirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirButtonMouseClicked(evt);
            }
        });
        jPanel1.add(salirButton);
        salirButton.setBounds(150, 330, 230, 48);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/fondo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 530, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirButtonMouseClicked

    private void productoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoButtonMouseClicked
        Producto.setModal(true);
        Producto.setTitle("Salman's Panadería y Repostería");
        Producto.setSize(630, 450);
        Producto.setLocationRelativeTo(null);
        Producto.setVisible(true);
    }//GEN-LAST:event_productoButtonMouseClicked

    private void tf_nombreProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreProdActionPerformed

    private void ok_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_AgregarMouseClicked
        
        if(tf_nombreProd.getText().equals("") || (Integer)spinner_precio.getValue() == 0 || (Integer)spinner_tiempo.getValue() == 0 || tempIngredientes.isEmpty()){
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
        }
        
        else{
            String name = tf_nombreProd.getText();
            int precio = (Integer)spinner_precio.getValue();
            int time = (Integer)spinner_tiempo.getValue();
            
            productos.add(new Product(name,tempIngredientes,(double)precio,time));
            JOptionPane.showMessageDialog(this, "Producto agregado exitosamente!");
            
            tf_nombreProd.setText("");
            spinner_precio.setValue(0);
            spinner_tiempo.setValue(0);
            cb_prodAdd.setSelectedIndex(0);
           
            DefaultTableModel model = (DefaultTableModel)tabla_nProd.getModel(); 
            int rows = model.getRowCount(); 
            for(int i = rows - 1; i >=0; i--){
               model.removeRow(i); 
            }
            tabla_nProd.setModel(model);
        }
    }//GEN-LAST:event_ok_AgregarMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        tempIngredientes.add((Ingrediente)cb_prodAdd.getSelectedItem());
        DefaultTableModel model = (DefaultTableModel)tabla_nProd.getModel();
        Object[] row = {((Ingrediente)cb_prodAdd.getSelectedItem()).getName(),((Ingrediente)cb_prodAdd.getSelectedItem()).getDesc()};
        model.addRow(row);
        tabla_nProd.setModel(model);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void tf_modNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_modNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_modNameActionPerformed

    private void ok_ModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_ModMouseClicked
       
        
        Product select = (Product)cb_modProd.getSelectedItem();
        select.setName(tf_modName.getText());
        select.setPrice((Double)spinner_modPrice.getValue());
        select.setTime((Integer)spinner_modTime.getValue());
        
        JOptionPane.showMessageDialog(this, "Producto modificado!");
        cb_modProd.removeAllItems();
        tabla_modProd.removeAll();
        
        for (Product producto : productos) {
            cb_modProd.addItem(producto);
        }
        
        if(productos.size() >= 1){
            warning.setVisible(false);
            Product selection = (Product)cb_modProd.getSelectedItem();
            tf_modName.setText(selection.getName());
            spinner_modPrice.setValue(selection.getPrice());
            spinner_modTime.setValue(selection.getTime());
            ArrayList temp = selection.getIngredients();
            
            DefaultTableModel model = (DefaultTableModel)tabla_modProd.getModel();
            for(int i = 0; i < temp.size(); i++){
                Object[] row = {((Ingrediente)temp.get(i)).getName(),((Ingrediente)temp.get(i)).getDesc()};
                model.addRow(row);
            }
            tabla_modProd.setModel(model);
            
            panel_add.setVisible(false);
            panel_del.setVisible(false);
            panel_mod.setVisible(true);
        }
        
        else{
            warning.setVisible(true);
        }
        
    }//GEN-LAST:event_ok_ModMouseClicked

    private void cb_modProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_modProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_modProdActionPerformed

    private void ok_Agregar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_Agregar2MouseClicked
        cb_delProd.removeAllItems();
        for (Product producto : productos) {
            cb_delProd.addItem(producto);
        }
        
        productos.remove((Product)cb_delProd.getSelectedItem());
        JOptionPane.showMessageDialog(this,"Producto Eliminado!");
       
        cb_delProd.removeAllItems();
        for (Product producto : productos) {
            cb_delProd.addItem(producto);
        }
    }//GEN-LAST:event_ok_Agregar2MouseClicked

    private void cb_delProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_delProdActionPerformed
        
    }//GEN-LAST:event_cb_delProdActionPerformed

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
       panel_add.setVisible(true);
       panel_del.setVisible(false);
       panel_mod.setVisible(false);
       warning.setVisible(false);
    }//GEN-LAST:event_agregarMouseClicked

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
       
        cb_modProd.removeAllItems();
        tabla_modProd.removeAll();
        
        for (Product producto : productos) {
            cb_modProd.addItem(producto);
        }
        
        if(productos.size() >= 1){
            warning.setVisible(false);
            Product selection = (Product)cb_modProd.getSelectedItem();
            tf_modName.setText(selection.getName());
            spinner_modPrice.setValue(selection.getPrice());
            spinner_modTime.setValue(selection.getTime());
            ArrayList temp = selection.getIngredients();
            
            DefaultTableModel model = (DefaultTableModel)tabla_modProd.getModel();
            for(int i = 0; i < temp.size(); i++){
                Object[] row = {((Ingrediente)temp.get(i)).getName(),((Ingrediente)temp.get(i)).getDesc()};
                model.addRow(row);
            }
            tabla_modProd.setModel(model);
            
            panel_add.setVisible(false);
            panel_del.setVisible(false);
            panel_mod.setVisible(true);
        }
        
        else{
            warning.setVisible(true);
        }
        
    }//GEN-LAST:event_modificarMouseClicked

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
       panel_add.setVisible(false);
       panel_del.setVisible(true);
       panel_mod.setVisible(false);
       
       cb_delProd.removeAllItems();
       for(Product product:productos){
           cb_delProd.addItem(product);
       }
    }//GEN-LAST:event_eliminarMouseClicked

    private void ok_Agregar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_Agregar3MouseClicked
        if(stackIngredientes.size() > 1){
            stackIngredientes.removeElementAt(cb_delProd.getSelectedIndex());
            cb_delIng.removeItemAt(cb_delIng.getSelectedIndex());
            JOptionPane.showMessageDialog(this,"Ingrediente eliminado exitosamente!");
        }
        else
            JOptionPane.showMessageDialog(this, "No hay ingredientes");
    }//GEN-LAST:event_ok_Agregar3MouseClicked

    private void agregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar1MouseClicked
       panel_remIng.setVisible(false);
       panel_addIng.setVisible(true);
    }//GEN-LAST:event_agregar1MouseClicked

    private void eliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar1MouseClicked
       panel_remIng.setVisible(true);
       panel_addIng.setVisible(false);
       
       cb_delIng.removeAllItems();
        for (Object stackIngrediente : stackIngredientes) {
                cb_delIng.addItem(stackIngrediente);
        }
       
    }//GEN-LAST:event_eliminar1MouseClicked

    private void ok_Agregar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_Agregar4MouseClicked
        if(tf_nameIng.getText().equals("") || tf_desc.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Llene todos los campos");
        }
        else{
            
            cb_prodAdd.removeAllItems();
            stackIngredientes.push(new Ingrediente(tf_nameIng.getText(),tf_desc.getText()));
            JOptionPane.showMessageDialog(this, "Ingrediente agregado exitosamente!");
            
            for (Object stackIngrediente : stackIngredientes) {
                cb_prodAdd.addItem(stackIngrediente);
            }
            
            tf_nameIng.setText("");
            tf_desc.setText("");
        }
    }//GEN-LAST:event_ok_Agregar4MouseClicked

    private void cb_delIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_delIngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_delIngActionPerformed

    private void ingredienteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingredienteButtonMouseClicked
        Ingrediente.pack();
        Ingrediente.setModal(true);
        Ingrediente.setSize(610,325);
        Ingrediente.setTitle("Salman´s Panadería y Repostería");
        Ingrediente.setLocationRelativeTo(null);
        Ingrediente.setVisible(true);
    }//GEN-LAST:event_ingredienteButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Ingrediente;
    private javax.swing.JDialog Producto;
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel agregar1;
    private javax.swing.JComboBox cb_delIng;
    private javax.swing.JComboBox cb_delProd;
    private javax.swing.JComboBox cb_modProd;
    private javax.swing.JComboBox cb_prodAdd;
    private javax.swing.JLabel cocinaButton;
    private javax.swing.JLabel eliminar;
    private javax.swing.JLabel eliminar1;
    private javax.swing.JLabel entregaButton;
    private javax.swing.JLabel ingredienteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel modificar;
    private javax.swing.JButton ok_Agregar;
    private javax.swing.JButton ok_Agregar2;
    private javax.swing.JButton ok_Agregar3;
    private javax.swing.JButton ok_Agregar4;
    private javax.swing.JButton ok_Mod;
    private javax.swing.JPanel panel_add;
    private javax.swing.JPanel panel_addIng;
    private javax.swing.JPanel panel_del;
    private javax.swing.JPanel panel_mod;
    private javax.swing.JPanel panel_remIng;
    private javax.swing.JLabel productoButton;
    private javax.swing.JLabel salirButton;
    private javax.swing.JSpinner spinner_modPrice;
    private javax.swing.JSpinner spinner_modTime;
    private javax.swing.JSpinner spinner_precio;
    private javax.swing.JSpinner spinner_tiempo;
    private javax.swing.JTable tabla_modProd;
    private javax.swing.JTable tabla_nProd;
    private javax.swing.JTextField tf_desc;
    private javax.swing.JTextField tf_modName;
    private javax.swing.JTextField tf_nameIng;
    private javax.swing.JTextField tf_nombreProd;
    private javax.swing.JPanel warning;
    // End of variables declaration//GEN-END:variables
    ArrayList tempIngredientes = new ArrayList();
    ArrayList <Product> productos = new ArrayList();
    Stack stackIngredientes = new Stack();
            
}
