package salmans;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Oscar
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        orderSystem.setVisible(false);
        panel_add.setVisible(true);
        panel_mod.setVisible(false);
        panel_del.setVisible(false);
        warning.setVisible(false);
        panel_remIng.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Producto = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        panel_add = new javax.swing.JPanel();
        tf_nombreProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spinner_precio = new javax.swing.JSpinner();
        cb_prodAdd = new javax.swing.JComboBox();
        spinner_tiempo = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_nProd = new javax.swing.JTable();
        ok_Agregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panel_mod = new javax.swing.JPanel();
        tf_modName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        spinner_modPrice = new javax.swing.JSpinner();
        spinner_modTime = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_modProd = new javax.swing.JTable();
        ok_Mod = new javax.swing.JButton();
        cb_modProd = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        panel_del = new javax.swing.JPanel();
        ok_Agregar2 = new javax.swing.JButton();
        cb_delProd = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        warning = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        modificar = new javax.swing.JLabel();
        agregar = new javax.swing.JLabel();
        eliminar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Ingrediente = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        panel_addIng = new javax.swing.JPanel();
        ok_Agregar4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        tf_nameIng = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_desc = new javax.swing.JTextField();
        panel_remIng = new javax.swing.JPanel();
        ok_Agregar3 = new javax.swing.JButton();
        cb_delIng = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        agregar1 = new javax.swing.JLabel();
        eliminar1 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Cocina = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        newOrder = new javax.swing.JLabel();
        OrderSys = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        panel_orden = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_order = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf_cliente = new javax.swing.JTextField();
        tf_number = new javax.swing.JTextField();
        cb_cocinaProd = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        sp_cantidad = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        cooks = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        jl_total = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        orderSystem = new javax.swing.JPanel();
        Ventas = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_ventas = new javax.swing.JTable();
        tot_ventas = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productoButton = new javax.swing.JLabel();
        ingredienteButton = new javax.swing.JLabel();
        cocinaButton = new javax.swing.JLabel();
        entregaButton = new javax.swing.JLabel();
        cierreButton = new javax.swing.JLabel();
        salirButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.setLayout(null);

        panel_add.setOpaque(false);
        panel_add.setLayout(null);

        tf_nombreProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreProdActionPerformed(evt);
            }
        });
        panel_add.add(tf_nombreProd);
        tf_nombreProd.setBounds(150, 20, 130, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/nombre.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        panel_add.add(jLabel5);
        jLabel5.setBounds(30, 20, 110, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/precio.jpg"))); // NOI18N
        panel_add.add(jLabel6);
        jLabel6.setBounds(30, 60, 110, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/ingredientes.jpg"))); // NOI18N
        panel_add.add(jLabel8);
        jLabel8.setBounds(30, 100, 110, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/tiempo.jpg"))); // NOI18N
        panel_add.add(jLabel9);
        jLabel9.setBounds(30, 210, 130, 30);

        spinner_precio.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 5));
        panel_add.add(spinner_precio);
        spinner_precio.setBounds(150, 60, 70, 30);

        panel_add.add(cb_prodAdd);
        cb_prodAdd.setBounds(150, 100, 110, 30);

        spinner_tiempo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 10));
        panel_add.add(spinner_tiempo);
        spinner_tiempo.setBounds(170, 210, 70, 30);

        tabla_nProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tabla_nProd);

        panel_add.add(jScrollPane1);
        jScrollPane1.setBounds(30, 140, 250, 60);

        ok_Agregar.setText("OK");
        ok_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_AgregarMouseClicked(evt);
            }
        });
        panel_add.add(ok_Agregar);
        ok_Agregar.setBounds(110, 250, 90, 26);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/plus.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panel_add.add(jLabel3);
        jLabel3.setBounds(260, 100, 30, 30);

        jPanel2.add(panel_add);
        panel_add.setBounds(50, 100, 300, 290);

        panel_mod.setOpaque(false);
        panel_mod.setLayout(null);

        tf_modName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_modNameActionPerformed(evt);
            }
        });
        panel_mod.add(tf_modName);
        tf_modName.setBounds(150, 60, 130, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/nombre.jpg"))); // NOI18N
        jLabel11.setText("jLabel5");
        panel_mod.add(jLabel11);
        jLabel11.setBounds(30, 60, 110, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/precio.jpg"))); // NOI18N
        panel_mod.add(jLabel12);
        jLabel12.setBounds(30, 100, 110, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/tiempo.jpg"))); // NOI18N
        panel_mod.add(jLabel14);
        jLabel14.setBounds(30, 210, 130, 30);

        spinner_modPrice.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 5));
        panel_mod.add(spinner_modPrice);
        spinner_modPrice.setBounds(150, 100, 70, 30);

        spinner_modTime.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 10));
        panel_mod.add(spinner_modTime);
        spinner_modTime.setBounds(170, 210, 70, 30);

        tabla_modProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripción"
            }
        ));
        jScrollPane2.setViewportView(tabla_modProd);

        panel_mod.add(jScrollPane2);
        jScrollPane2.setBounds(30, 140, 250, 60);

        ok_Mod.setText("OK");
        ok_Mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_ModMouseClicked(evt);
            }
        });
        panel_mod.add(ok_Mod);
        ok_Mod.setBounds(110, 260, 90, 26);

        cb_modProd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_modProd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_modProdItemStateChanged(evt);
            }
        });
        cb_modProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_modProdActionPerformed(evt);
            }
        });
        panel_mod.add(cb_modProd);
        cb_modProd.setBounds(140, 20, 140, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/select.png"))); // NOI18N
        panel_mod.add(jLabel16);
        jLabel16.setBounds(30, 20, 110, 30);

        jPanel2.add(panel_mod);
        panel_mod.setBounds(50, 100, 300, 290);

        panel_del.setOpaque(false);
        panel_del.setLayout(null);

        ok_Agregar2.setText("OK");
        ok_Agregar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_Agregar2MouseClicked(evt);
            }
        });
        panel_del.add(ok_Agregar2);
        ok_Agregar2.setBounds(100, 120, 90, 30);

        cb_delProd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_delProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_delProdActionPerformed(evt);
            }
        });
        panel_del.add(cb_delProd);
        cb_delProd.setBounds(150, 80, 140, 30);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/select.png"))); // NOI18N
        panel_del.add(jLabel22);
        jLabel22.setBounds(40, 80, 110, 30);

        jPanel2.add(panel_del);
        panel_del.setBounds(50, 100, 300, 290);

        warning.setOpaque(false);
        warning.setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/warning.png"))); // NOI18N
        warning.add(jLabel13);
        jLabel13.setBounds(270, 0, 30, 30);

        jLabel10.setFont(new java.awt.Font("Bangers", 1, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NO HAY PRODUCTOS ");
        warning.add(jLabel10);
        jLabel10.setBounds(50, 0, 230, 30);

        jPanel2.add(warning);
        warning.setBounds(50, 100, 300, 290);

        jLabel7.setFont(new java.awt.Font("Bangers", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRODUCTO");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(220, 30, 220, 70);

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/modificar.png"))); // NOI18N
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });
        jPanel2.add(modificar);
        modificar.setBounds(380, 220, 240, 60);

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/add.png"))); // NOI18N
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });
        jPanel2.add(agregar);
        agregar.setBounds(380, 160, 240, 60);

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/eliminar.png"))); // NOI18N
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });
        jPanel2.add(eliminar);
        eliminar.setBounds(380, 280, 240, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/fondo.jpg"))); // NOI18N
        jLabel4.setText("jLabel2");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 620, 430);

        javax.swing.GroupLayout ProductoLayout = new javax.swing.GroupLayout(Producto.getContentPane());
        Producto.getContentPane().setLayout(ProductoLayout);
        ProductoLayout.setHorizontalGroup(
            ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        ProductoLayout.setVerticalGroup(
            ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setLayout(null);

        panel_addIng.setOpaque(false);
        panel_addIng.setLayout(null);

        ok_Agregar4.setText("OK");
        ok_Agregar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_Agregar4MouseClicked(evt);
            }
        });
        panel_addIng.add(ok_Agregar4);
        ok_Agregar4.setBounds(110, 110, 90, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/nombre.jpg"))); // NOI18N
        panel_addIng.add(jLabel15);
        jLabel15.setBounds(30, 30, 120, 20);
        panel_addIng.add(tf_nameIng);
        tf_nameIng.setBounds(160, 30, 110, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/desc.png"))); // NOI18N
        panel_addIng.add(jLabel17);
        jLabel17.setBounds(30, 70, 120, 20);
        panel_addIng.add(tf_desc);
        tf_desc.setBounds(160, 70, 110, 30);

        jPanel3.add(panel_addIng);
        panel_addIng.setBounds(50, 100, 300, 160);

        panel_remIng.setOpaque(false);
        panel_remIng.setLayout(null);

        ok_Agregar3.setText("OK");
        ok_Agregar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_Agregar3MouseClicked(evt);
            }
        });
        panel_remIng.add(ok_Agregar3);
        ok_Agregar3.setBounds(100, 90, 90, 30);

        cb_delIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_delIngActionPerformed(evt);
            }
        });
        panel_remIng.add(cb_delIng);
        cb_delIng.setBounds(140, 40, 140, 30);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/select.png"))); // NOI18N
        panel_remIng.add(jLabel26);
        jLabel26.setBounds(30, 40, 110, 30);

        jPanel3.add(panel_remIng);
        panel_remIng.setBounds(50, 100, 300, 160);

        jLabel29.setFont(new java.awt.Font("Bangers", 1, 48)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("ingredientes");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(190, 30, 270, 70);

        agregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/add.png"))); // NOI18N
        agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar1MouseClicked(evt);
            }
        });
        jPanel3.add(agregar1);
        agregar1.setBounds(380, 120, 240, 60);

        eliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/eliminar.png"))); // NOI18N
        eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar1MouseClicked(evt);
            }
        });
        jPanel3.add(eliminar1);
        eliminar1.setBounds(380, 180, 240, 60);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/fondo.jpg"))); // NOI18N
        jLabel30.setText("jLabel2");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(0, 0, 620, 290);

        javax.swing.GroupLayout IngredienteLayout = new javax.swing.GroupLayout(Ingrediente.getContentPane());
        Ingrediente.getContentPane().setLayout(IngredienteLayout);
        IngredienteLayout.setHorizontalGroup(
            IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngredienteLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        IngredienteLayout.setVerticalGroup(
            IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngredienteLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setLayout(null);

        newOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/newOrder.png"))); // NOI18N
        newOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newOrderMouseClicked(evt);
            }
        });
        jPanel4.add(newOrder);
        newOrder.setBounds(80, 100, 201, 38);

        OrderSys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/orderSys.png"))); // NOI18N
        OrderSys.setText("jLabel20");
        OrderSys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderSysMouseClicked(evt);
            }
        });
        jPanel4.add(OrderSys);
        OrderSys.setBounds(290, 100, 200, 40);

        jLabel31.setFont(new java.awt.Font("Bangers", 1, 48)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("cocina");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(220, 40, 150, 50);

        panel_orden.setOpaque(false);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/cliente.png"))); // NOI18N

        tabla_order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla_order);
        if (tabla_order.getColumnModel().getColumnCount() > 0) {
            tabla_order.getColumnModel().getColumn(0).setResizable(false);
            tabla_order.getColumnModel().getColumn(0).setHeaderValue("Producto");
            tabla_order.getColumnModel().getColumn(1).setHeaderValue("Precio");
        }

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/number.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/orderProd.png"))); // NOI18N

        jButton1.setText("OK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        tf_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_numberKeyTyped(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/plus.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/cantidad.png"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/cocineros.png"))); // NOI18N

        cooks.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/total.png"))); // NOI18N

        jl_total.setFont(new java.awt.Font("Bangers", 1, 20)); // NOI18N
        jl_total.setForeground(new java.awt.Color(255, 255, 255));
        jl_total.setText("Lps. 0.00");

        javax.swing.GroupLayout panel_ordenLayout = new javax.swing.GroupLayout(panel_orden);
        panel_orden.setLayout(panel_ordenLayout);
        panel_ordenLayout.setHorizontalGroup(
            panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ordenLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_ordenLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ordenLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cooks, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel21)
                        .addGroup(panel_ordenLayout.createSequentialGroup()
                            .addComponent(cb_cocinaProd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)
                            .addComponent(sp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)
                            .addComponent(jLabel23))
                        .addGroup(panel_ordenLayout.createSequentialGroup()
                            .addGroup(panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_cliente)
                                .addComponent(tf_number, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_ordenLayout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(57, 57, 57))
        );
        panel_ordenLayout.setVerticalGroup(
            panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ordenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ordenLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(panel_ordenLayout.createSequentialGroup()
                        .addGroup(panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_cliente)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_number)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sp_cantidad)
                                .addComponent(cb_cocinaProd)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cooks))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.add(panel_orden);
        panel_orden.setBounds(30, 150, 550, 240);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/fondo.jpg"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(0, 0, 600, 410);

        orderSystem.setOpaque(false);

        javax.swing.GroupLayout orderSystemLayout = new javax.swing.GroupLayout(orderSystem);
        orderSystem.setLayout(orderSystemLayout);
        orderSystemLayout.setHorizontalGroup(
            orderSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        orderSystemLayout.setVerticalGroup(
            orderSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel4.add(orderSystem);
        orderSystem.setBounds(30, 150, 550, 240);

        javax.swing.GroupLayout CocinaLayout = new javax.swing.GroupLayout(Cocina.getContentPane());
        Cocina.getContentPane().setLayout(CocinaLayout);
        CocinaLayout.setHorizontalGroup(
            CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        CocinaLayout.setVerticalGroup(
            CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        jPanel5.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Bangers", 1, 40)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("ventas");
        jPanel5.add(jLabel32);
        jLabel32.setBounds(140, 40, 110, 44);

        tabla_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Pago"
            }
        ));
        jScrollPane4.setViewportView(tabla_ventas);

        jPanel5.add(jScrollPane4);
        jScrollPane4.setBounds(40, 100, 310, 130);

        tot_ventas.setFont(new java.awt.Font("Bangers", 1, 18)); // NOI18N
        tot_ventas.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(tot_ventas);
        tot_ventas.setBounds(250, 250, 90, 20);

        jLabel33.setFont(new java.awt.Font("Bangers", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Total en Ventas del día: ");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(60, 250, 190, 20);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/fondo.jpg"))); // NOI18N
        jPanel5.add(jLabel28);
        jLabel28.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout VentasLayout = new javax.swing.GroupLayout(Ventas.getContentPane());
        Ventas.getContentPane().setLayout(VentasLayout);
        VentasLayout.setHorizontalGroup(
            VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        VentasLayout.setVerticalGroup(
            VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/logo.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 30, 540, 120);

        productoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/producto.png"))); // NOI18N
        productoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productoButtonMouseClicked(evt);
            }
        });
        jPanel1.add(productoButton);
        productoButton.setBounds(0, 190, 250, 50);

        ingredienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/ingredientes.png"))); // NOI18N
        ingredienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingredienteButtonMouseClicked(evt);
            }
        });
        jPanel1.add(ingredienteButton);
        ingredienteButton.setBounds(0, 260, 250, 48);

        cocinaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/cocina.png"))); // NOI18N
        cocinaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cocinaButtonMouseClicked(evt);
            }
        });
        jPanel1.add(cocinaButton);
        cocinaButton.setBounds(280, 190, 250, 50);

        entregaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/entregas.png"))); // NOI18N
        jPanel1.add(entregaButton);
        entregaButton.setBounds(280, 260, 250, 48);

        cierreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/cierre.png"))); // NOI18N
        cierreButton.setText("jLabel28");
        cierreButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cierreButtonMouseClicked(evt);
            }
        });
        jPanel1.add(cierreButton);
        cierreButton.setBounds(0, 330, 250, 50);

        salirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/salir.png"))); // NOI18N
        salirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirButtonMouseClicked(evt);
            }
        });
        jPanel1.add(salirButton);
        salirButton.setBounds(280, 330, 250, 48);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panaderia/fondo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 530, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirButtonMouseClicked

    private void productoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoButtonMouseClicked
       cb_prodAdd.removeAllItems();
        for (Object stackIngrediente : stackIngredientes) {
            cb_prodAdd.addItem(stackIngrediente);
        }
        
        Producto.setModal(true);
        Producto.setTitle("Salman's Panadería y Repostería");
        Producto.setSize(630, 450);
        Producto.setLocationRelativeTo(null);
        Producto.setVisible(true);
        
    }//GEN-LAST:event_productoButtonMouseClicked

    private void tf_nombreProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreProdActionPerformed

    private void ok_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_AgregarMouseClicked
        
        if(tf_nombreProd.getText().equals("") || (Integer)spinner_precio.getValue() == 0 || (Integer)spinner_tiempo.getValue() == 0 || tempIngredientes.isEmpty()){
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
        }
        
        else{
            String name = tf_nombreProd.getText();
            int precio = (Integer)spinner_precio.getValue();
            int time = (Integer)spinner_tiempo.getValue();
            
            productos.add(new Product(name,tempIngredientes,(double)precio,time));
            tempIngredientes.clear();
            JOptionPane.showMessageDialog(this, "Producto agregado exitosamente!");
            
            tf_nombreProd.setText("");
            spinner_precio.setValue(0);
            spinner_tiempo.setValue(0);
            cb_prodAdd.setSelectedIndex(0);
           
            DefaultTableModel model = (DefaultTableModel)tabla_nProd.getModel(); 
            int rows = model.getRowCount(); 
            for(int i = rows - 1; i >=0; i--){
               model.removeRow(i); 
            }
            tabla_nProd.setModel(model);
        }
    }//GEN-LAST:event_ok_AgregarMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        tempIngredientes.add((Ingrediente)cb_prodAdd.getSelectedItem());
        DefaultTableModel model = (DefaultTableModel)tabla_nProd.getModel();
        Object[] row = {((Ingrediente)cb_prodAdd.getSelectedItem()).getName(),((Ingrediente)cb_prodAdd.getSelectedItem()).getDesc()};
        model.addRow(row);
        tabla_nProd.setModel(model);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void tf_modNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_modNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_modNameActionPerformed

    private void ok_ModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_ModMouseClicked
       
        
        Product select = (Product)cb_modProd.getSelectedItem();
        select.setName(tf_modName.getText());
        select.setPrice((Double)spinner_modPrice.getValue());
        select.setTime((Integer)spinner_modTime.getValue());
        
        JOptionPane.showMessageDialog(this, "Producto modificado!");
        cb_modProd.removeAllItems();
        tabla_modProd.removeAll();
        
        for (Product producto : productos) {
            cb_modProd.addItem(producto);
        }
        
        if(productos.size() >= 1){
            warning.setVisible(false);
            Product selection = (Product)cb_modProd.getSelectedItem();
            tf_modName.setText(selection.getName());
            spinner_modPrice.setValue(selection.getPrice());
            spinner_modTime.setValue(selection.getTime());
            ArrayList temp = selection.getIngredients();
            
            DefaultTableModel model = (DefaultTableModel)tabla_modProd.getModel();
            for(int i = 0; i < temp.size(); i++){
                Object[] row = {((Ingrediente)temp.get(i)).getName(),((Ingrediente)temp.get(i)).getDesc()};
                model.addRow(row);
            }
            tabla_modProd.setModel(model);
            
            panel_add.setVisible(false);
            panel_del.setVisible(false);
            panel_mod.setVisible(true);
        }
        
        else{
            warning.setVisible(true);
        }
        
    }//GEN-LAST:event_ok_ModMouseClicked

    private void cb_modProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_modProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_modProdActionPerformed

    private void ok_Agregar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_Agregar2MouseClicked
        productos.remove(cb_delProd.getSelectedIndex());
        cb_delProd.remove(cb_delProd.getSelectedIndex());
        JOptionPane.showMessageDialog(this,"Producto Eliminado!");
    }//GEN-LAST:event_ok_Agregar2MouseClicked

    private void cb_delProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_delProdActionPerformed
        
    }//GEN-LAST:event_cb_delProdActionPerformed

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
       panel_add.setVisible(true);
       panel_del.setVisible(false);
       panel_mod.setVisible(false);
       warning.setVisible(false);
    }//GEN-LAST:event_agregarMouseClicked

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
       
        cb_modProd.removeAllItems();
        tabla_modProd.removeAll();
        
        for (Product producto : productos) {
            cb_modProd.addItem(producto);
        }
        
        if(productos.size() >= 1){
            warning.setVisible(false);
            Product selection = (Product)cb_modProd.getSelectedItem();
            tf_modName.setText(selection.getName());
            spinner_modPrice.setValue(selection.getPrice());
            spinner_modTime.setValue(selection.getTime());
            ArrayList temp = selection.getIngredients();
            
            DefaultTableModel model = (DefaultTableModel)tabla_modProd.getModel();
            for(int i = 0; i < temp.size(); i++){
                Object[] row = {((Ingrediente)temp.get(i)).getName(),((Ingrediente)temp.get(i)).getDesc()};
                model.addRow(row);
            }
            tabla_modProd.setModel(model);
            
            panel_add.setVisible(false);
            panel_del.setVisible(false);
            panel_mod.setVisible(true);
        }
        
        else{
            warning.setVisible(true);
        }
        
    }//GEN-LAST:event_modificarMouseClicked

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
       panel_add.setVisible(false);
       panel_del.setVisible(true);
       panel_mod.setVisible(false);
       
       cb_delProd.removeAllItems();
       for(Product product:productos){
           cb_delProd.addItem(product);
       }
    }//GEN-LAST:event_eliminarMouseClicked

    private void ok_Agregar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_Agregar3MouseClicked
        if(stackIngredientes.size() > 1){
            stackIngredientes.removeElementAt(cb_delProd.getSelectedIndex());
            cb_delIng.removeItemAt(cb_delIng.getSelectedIndex());
            JOptionPane.showMessageDialog(this,"Ingrediente eliminado exitosamente!");
        }
        else
            JOptionPane.showMessageDialog(this, "No hay ingredientes");
    }//GEN-LAST:event_ok_Agregar3MouseClicked

    private void agregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar1MouseClicked
       panel_remIng.setVisible(false);
       panel_addIng.setVisible(true);
    }//GEN-LAST:event_agregar1MouseClicked

    private void eliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar1MouseClicked
       panel_remIng.setVisible(true);
       panel_addIng.setVisible(false);
       
       cb_delIng.removeAllItems();
        for (Object stackIngrediente : stackIngredientes) {
                cb_delIng.addItem(stackIngrediente);
        }
       
    }//GEN-LAST:event_eliminar1MouseClicked

    private void ok_Agregar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_Agregar4MouseClicked
        if(tf_nameIng.getText().equals("") || tf_desc.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Llene todos los campos");
        }
        else{
            
            stackIngredientes.push(new Ingrediente(tf_nameIng.getText(),tf_desc.getText()));
            JOptionPane.showMessageDialog(this, "Ingrediente agregado exitosamente!");
            
            tf_nameIng.setText("");
            tf_desc.setText("");
        }
    }//GEN-LAST:event_ok_Agregar4MouseClicked

    private void cb_delIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_delIngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_delIngActionPerformed

    private void ingredienteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingredienteButtonMouseClicked
        Ingrediente.pack();
        Ingrediente.setModal(true);
        Ingrediente.setSize(610,325);
        Ingrediente.setTitle("Salman´s Panadería y Repostería");
        Ingrediente.setLocationRelativeTo(null);
        Ingrediente.setVisible(true);
    }//GEN-LAST:event_ingredienteButtonMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(tf_cliente.getText().equals("") || tf_number.getText().equals("") || (Integer)sp_cantidad.getValue() == 0 || (Integer)cooks.getValue() == 0 || tabla_order.getRowCount() == 0){
             JOptionPane.showMessageDialog(this,"Llene todos los campos");
        }
        else{
           ordenes.add(new Orden(tf_cliente.getText(),Integer.parseInt(tf_number.getText()),tempProductos,total,(Integer)cooks.getValue()));
           JOptionPane.showMessageDialog(this, "Orden agregada!");
           
           tf_cliente.setText("");
           tf_number.setText("");
           sp_cantidad.setValue(0);
           cb_cocinaProd.setSelectedIndex(0);
           cooks.setValue(1);
           tempProductos.clear();
           total = 0;
           
           DefaultTableModel model = (DefaultTableModel)tabla_order.getModel(); 
            int rows = model.getRowCount(); 
            for(int i = rows - 1; i >=0; i--){
               model.removeRow(i); 
            }
            tabla_order.setModel(model);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void cocinaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cocinaButtonMouseClicked
        cb_cocinaProd.removeAllItems();
        
        for(Product producto:productos){
            cb_cocinaProd.addItem(producto);
        }
        
        Cocina.pack();
        Cocina.setModal(true);
        Cocina.setSize(600,430);
        Cocina.setTitle("Salman´s Panadería y Repostería");
        Cocina.setLocationRelativeTo(null);
        Cocina.setVisible(true);
    }//GEN-LAST:event_cocinaButtonMouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        tempProductos.add((Product)cb_cocinaProd.getSelectedItem());
        int cant = (Integer)sp_cantidad.getValue();
        
        DefaultTableModel model = (DefaultTableModel)tabla_order.getModel();
        Object[] row = {((Product)cb_cocinaProd.getSelectedItem()).getName(),((Product)cb_cocinaProd.getSelectedItem()).getPrice(),cant};
        model.addRow(row);
        tabla_order.setModel(model);
        total += ((Product)cb_cocinaProd.getSelectedItem()).getPrice() * (Integer)sp_cantidad.getValue();
        jl_total.setText("Lps." + total + "0");
        sp_cantidad.setValue(1);
           
    }//GEN-LAST:event_jLabel23MouseClicked

    private void tf_numberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_numberKeyTyped
       char c = evt.getKeyChar();
       if(!Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE){
           evt.consume();
       }
    }//GEN-LAST:event_tf_numberKeyTyped

    private void newOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newOrderMouseClicked
        panel_orden.setVisible(true);
        orderSystem.setVisible(false);
    }//GEN-LAST:event_newOrderMouseClicked

    private void OrderSysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderSysMouseClicked
        panel_orden.setVisible(false);
        orderSystem.setVisible(true);
    }//GEN-LAST:event_OrderSysMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
    
    }//GEN-LAST:event_jPanel1MouseClicked

    private void cierreButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cierreButtonMouseClicked
       DefaultTableModel model = (DefaultTableModel)tabla_ventas.getModel();
       double total_ventas = 0.0;
        for(Orden order : ordenes){
           Object[] row = {order.getClient(),order.getTotal()};
           model.addRow(row);
           total_ventas += order.getTotal();
       }
       tabla_ventas.setModel(model);
       tot_ventas.setText("Lps." + total_ventas + "0");
       
        Ventas.pack();
        Ventas.setModal(true);
        Ventas.setSize(400,338);
        Ventas.setTitle("Salman´s Panadería y Repostería");
        Ventas.setLocationRelativeTo(null);
        Ventas.setVisible(true);
    }//GEN-LAST:event_cierreButtonMouseClicked

    private void cb_modProdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_modProdItemStateChanged
     if(cb_modProd.getSelectedIndex() > 0){
        tf_modName.setText(((Product)cb_modProd.getSelectedItem()).getName());
        spinner_modPrice.setValue(((Product)cb_modProd.getSelectedItem()).getPrice());
        spinner_modTime.setValue(((Product)cb_modProd.getSelectedItem()).getTime());
        
        DefaultTableModel model = (DefaultTableModel)tabla_modProd.getModel();
        for(int i = 0; i < model.getRowCount(); i++){
            model.removeRow(i);
        }
        tabla_modProd.setModel(model);
        model = (DefaultTableModel)tabla_modProd.getModel();
        
        for(int i = 0; i < ((Product)cb_modProd.getSelectedItem()).getIngredients().size(); i++){
            Object[] row = {((Product)cb_modProd.getSelectedItem()).getIngredients().get(i).getName(),((Product)cb_modProd.getSelectedItem()).getIngredients().get(i).getDesc()};
            model.addRow(row);
            System.out.println("row" + i);
        }
        tabla_modProd.setModel(model);
     }

    }//GEN-LAST:event_cb_modProdItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Cocina;
    private javax.swing.JDialog Ingrediente;
    private javax.swing.JLabel OrderSys;
    private javax.swing.JDialog Producto;
    private javax.swing.JDialog Ventas;
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel agregar1;
    private javax.swing.JComboBox cb_cocinaProd;
    private javax.swing.JComboBox cb_delIng;
    private javax.swing.JComboBox cb_delProd;
    private javax.swing.JComboBox cb_modProd;
    private javax.swing.JComboBox cb_prodAdd;
    private javax.swing.JLabel cierreButton;
    private javax.swing.JLabel cocinaButton;
    private javax.swing.JSpinner cooks;
    private javax.swing.JLabel eliminar;
    private javax.swing.JLabel eliminar1;
    private javax.swing.JLabel entregaButton;
    private javax.swing.JLabel ingredienteButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jl_total;
    private javax.swing.JLabel modificar;
    private javax.swing.JLabel newOrder;
    private javax.swing.JButton ok_Agregar;
    private javax.swing.JButton ok_Agregar2;
    private javax.swing.JButton ok_Agregar3;
    private javax.swing.JButton ok_Agregar4;
    private javax.swing.JButton ok_Mod;
    private javax.swing.JPanel orderSystem;
    private javax.swing.JPanel panel_add;
    private javax.swing.JPanel panel_addIng;
    private javax.swing.JPanel panel_del;
    private javax.swing.JPanel panel_mod;
    private javax.swing.JPanel panel_orden;
    private javax.swing.JPanel panel_remIng;
    private javax.swing.JLabel productoButton;
    private javax.swing.JLabel salirButton;
    private javax.swing.JSpinner sp_cantidad;
    private javax.swing.JSpinner spinner_modPrice;
    private javax.swing.JSpinner spinner_modTime;
    private javax.swing.JSpinner spinner_precio;
    private javax.swing.JSpinner spinner_tiempo;
    private javax.swing.JTable tabla_modProd;
    private javax.swing.JTable tabla_nProd;
    private javax.swing.JTable tabla_order;
    private javax.swing.JTable tabla_ventas;
    private javax.swing.JTextField tf_cliente;
    private javax.swing.JTextField tf_desc;
    private javax.swing.JTextField tf_modName;
    private javax.swing.JTextField tf_nameIng;
    private javax.swing.JTextField tf_nombreProd;
    private javax.swing.JTextField tf_number;
    private javax.swing.JLabel tot_ventas;
    private javax.swing.JPanel warning;
    // End of variables declaration//GEN-END:variables
    ArrayList tempIngredientes = new ArrayList();
    ArrayList <Product> tempProductos = new ArrayList();
    ArrayList <Product> productos = new ArrayList();
    ArrayList <Orden> ordenes = new ArrayList();
    Stack stackIngredientes = new Stack();
    double total = 0;
            
}
